apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: windows-sample
  labels:
    app: windows-sample
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: windows-sample
    spec:
      domain:
        cpu:
          cores: 2
          model: cortex-a57
        resources:
          requests:
            memory: 4Gi
        features:
          acpi: {}
        clock:
          utc: {}
          timer:
            hpet:
              present: false
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
        firmware:
          bootloader:
            efi:
              secureBoot: false
        devices:
          disks:
            - name: osdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: osdisk
          emptyDisk:
            capacity: 30Gi
