apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.*
    helm:
      values: |
        expose:
          type: nodePort
          nodePort:
            ports:
              http:
                nodePort: 30085
          tls:
            enabled: false
        externalURL: http://192.168.1.105:30085
        harborAdminPassword: ""
        existingSecretAdminPassword: harbor-admin
        existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
        core:
          configureUserSettings: |-
            {
              "ext_endpoint": "http://192.168.1.105:30085",
              "auth_mode": "oidc_auth",
              "oidc_name": "Keycloak",
              "oidc_endpoint": "http://192.168.1.105:30083/realms/local-dc",
              "oidc_client_id": "harbor",
              "oidc_client_secret": "harbor-secret-change-me",
              "oidc_scope": "openid,profile,email,groups",
              "oidc_groups_claim": "groups",
              "oidc_admin_group": "admins",
              "oidc_auto_onboard": "true",
              "oidc_user_claim": "preferred_username"
            }
        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              size: 50Gi
            database:
              size: 5Gi
            redis:
              size: 1Gi
            trivy:
              size: 5Gi
        database:
          type: internal
        redis:
          type: internal
        trivy:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
