apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.*
    helm:
      values: |
        expose:
          type: nodePort
          nodePort:
            ports:
              http:
                nodePort: 30085
          tls:
            enabled: false
        externalURL: http://192.168.1.105:30085
        harborAdminPassword: ""
        existingSecretAdminPassword: harbor-admin
        existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              size: 50Gi
            database:
              size: 5Gi
            redis:
              size: 1Gi
            trivy:
              size: 5Gi
        database:
          type: internal
        redis:
          type: internal
        trivy:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
