apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app-config
  namespace: backstage
data:
  app-config.yaml: |
    app:
      title: Local DC - Developer Portal
      baseUrl: http://192.168.1.105:30081

    organization:
      name: Local Datacenter

    backend:
      baseUrl: http://192.168.1.105:30081
      listen:
        port: 7007
      csp:
        connect-src: ["'self'", 'http:', 'https:']
      cors:
        origin: '*'
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      database:
        client: better-sqlite3
        connection: ':memory:'
      reading:
        allow:
          - host: raw.githubusercontent.com

    auth:
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true

    catalog:
      rules:
        - allow: [Component, System, API, Resource, Location, Template, User, Group]
      locations:
        - type: url
          target: https://raw.githubusercontent.com/stevebestone/local-dc/main/backstage-templates/ubuntu-vm.yaml
        - type: url
          target: https://raw.githubusercontent.com/stevebestone/local-dc/main/backstage-templates/linuxmint-vm.yaml
