apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app-config
  namespace: platform
data:
  app-config.yaml: |
    app:
      title: Local DC - Developer Portal
      baseUrl: http://localhost:7007

    organization:
      name: Local Datacenter

    backend:
      baseUrl: http://localhost:7007
      listen:
        port: 7007
      csp:
        connect-src: ["'self'", 'http:', 'https:']
      cors:
        origin: '*'
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      database:
        client: better-sqlite3
        connection: ':memory:'
      reading:
        allow:
          - host: raw.githubusercontent.com

    auth:
      environment: development
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true
        oidc:
          development:
            metadataUrl: http://keycloak.keycloak.svc.cluster.local:8080/realms/local-dc/.well-known/openid-configuration
            clientId: backstage
            clientSecret: ${BACKSTAGE_OIDC_SECRET}
            prompt: auto
            signIn:
              resolvers:
                - resolver: emailMatchingUserEntityProfileEmail

    catalog:
      rules:
        - allow: [Component, System, API, Resource, Location, Template, User, Group]
      locations:
        - type: url
          target: https://raw.githubusercontent.com/stevebestone/local-dc/main/backstage-templates/org.yaml
        - type: url
          target: https://raw.githubusercontent.com/stevebestone/local-dc/main/backstage-templates/ubuntu-vm.yaml
        - type: url
          target: https://raw.githubusercontent.com/stevebestone/local-dc/main/backstage-templates/linuxmint-vm.yaml
