apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage
  namespace: platform
---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-sa-token
  namespace: platform
  annotations:
    kubernetes.io/service-account.name: backstage
type: kubernetes.io/service-account-token
